### ISSUE TITLE
Instance secret

### ISSUE THREAD

**Issue by zorvi** [lol768/XenForo-MCASSOC#27]
Were can i get instsnce secret??? On the xenforo site link doesnt work

**Comment by zorvi** [comment]
* instance

**Comment by lol768** [comment]
It's literally just a 32 character hexadecimal password. The link *does* work: https://jsbin.com/jadofehoqu/1/edit?html,js,output

Look at the right hand side. It says "Your freshly-generated instance secret is:" and offers a textbox, where you can copy it.

**Comment by zorvi** [comment]
Association error
There was an error while associating your account.
Additional details: signature invalid
Credentials in use{"site_id":"http:\/\/mineblockz.net\/index.php","instance_secret":"X","shared_secret":"X

**Comment by lol768** [comment]
the site ID should be **verbatim** the domain you typed into the MCassoc verification tool.

**Comment by zorvi** [comment]
Ok

**Comment by lol768** [comment]
That should be fine to stay as it is? Unless you're having trouble with crafatar?

**Comment by zorvi** [comment]
and this?
Server Error Log
Error Info
Exception: MCAssocsignature invalid - library/AssociationMc/MCAssoc.php:70
Generated By: Zorvi, Mar 6, 2017
Stack Trace
#0 /home/minebloc/web/mineblockz.net/public_html/library/AssociationMc/MCAssoc.php(88): AssociationMc_MCAssoc->verify('eyJ1c2VybmFtZSI...', '\x97^\xD4\xF1/h\xEA\x85l;\x11\xC8+\xA2\xE0...')
#1 /home/minebloc/web/mineblockz.net/public_html/library/AssociationMc/ControllerPublic/Confirm.php(36): AssociationMc_MCAssoc->unwrapData('eyJ1c2VybmFtZSI...')
#2 /home/minebloc/web/mineblockz.net/public_html/library/XenForo/FrontController.php(347): AssociationMc_ControllerPublic_Confirm->actionIndex()
#3 /home/minebloc/web/mineblockz.net/public_html/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#4 /home/minebloc/web/mineblockz.net/public_html/index.php(13): XenForo_FrontController->run()
#5 {main}
Request State
array(3) {
  ["url"] => string(77) "http://mineblockz.net/index.php?mc-association/confirm&stage=3&username=Zorvi"
  ["_GET"] => array(3) {
    ["mc-association/confirm"] => string(0) ""
    ["stage"] => string(1) "3"
    ["username"] => string(5) "Zorvi"
  }
  ["_POST"] => array(1) {
    ["data"] => string(192) "eyJ1c2VybmFtZSI6IlpvcnZpIiwidXVpZCI6Ijc0NmEwNzEzYmVhYjQxMzA4NzVhNTNjY2FlN2JkNWIxIiwibm93IjoxNDg4ODIxMDg3LCJrZXkiOiJXbTl5ZG1sa01FdEJ0LzJSVlhscGdWS05BeXp6Vkc1c0JBPT0ifabPAxTg0VRl6rrtTmNwPmKhPpTD"
  }
}

**Comment by lol768** [comment]
Do you consistently get that?

**Comment by zorvi** [comment]
Yes
